import SwiftUI

struct GroupSummaryPDFView: View {
    let group: Group
    let currencyCode: String

    private var totalSpent: Double {
        group.expenses.reduce(0) { $0 + $1.amount }
    }

    private var settlements: [Settlement] {
        BalanceCalculator.settlements(for: group)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            Text("SplitMate Summary")
                .font(.largeTitle)
                .fontWeight(.bold)

            Text(group.name)
                .font(.title)
                .fontWeight(.semibold)

            Divider()

            HStack {
                Text("Total Spent")
                Spacer()
                Text(totalSpent, format: .currency(code: currencyCode))
                    .fontWeight(.bold)
            }

            HStack {
                Text("Members")
                Spacer()
                Text("\(group.members.count)")
            }

            HStack {
                Text("Expenses")
                Spacer()
                Text("\(group.expenses.count)")
            }

            Divider()

            Text("Settle Up")
                .font(.title2)
                .fontWeight(.bold)

            if settlements.isEmpty {
                Text("All settled.")
                    .foregroundStyle(.secondary)
            } else {
                ForEach(settlements) { settlement in
                    HStack {
                        Text("\(settlement.from.name) → \(settlement.to.name)")
                        Spacer()
                        Text(settlement.amount, format: .currency(code: currencyCode))
                            .fontWeight(.semibold)
                    }
                }
            }

            Divider()

            Text("Expenses")
                .font(.title2)
                .fontWeight(.bold)

            ForEach(group.expenses.sorted { $0.date > $1.date }) { expense in
                VStack(alignment: .leading, spacing: 4) {
                    HStack {
                        Text(expense.title)
                            .fontWeight(.semibold)

                        Spacer()

                        Text(expense.amount, format: .currency(code: currencyCode))
                    }

                    Text("\(expense.category) • Paid by \(expense.paidBy?.name ?? "Unknown")")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Divider()
            }

            Spacer()

            Text("Generated by SplitMate")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding(32)
        .frame(width: 612, height: 792)
        .background(Color.white)
        .foregroundColor(.black)
    }
}
